services:
  server:
    build:
      context: ./Server/GreenHouseApi
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      - "23:23"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=greenhouse;Username=postgres;Password=postgres

  ml:
    build:
      context: ./ML
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - server
    environment:
      - API_URL=http://server:8080

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adgangskode_til_postgres
      POSTGRES_DB: greenhouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
