name: IoT Run Native Tests

on:
  push:
    branches: [ main ]
    paths: [ 'IOT/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'IOT/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hent kode
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Byg native tests
        working-directory: ./IOT/native_test
        run: make CONFIG=DEBUG native_tests

      - name: Kør native tests
        working-directory: ./IOT/native_test
        run: make CONFIG=DEBUG run_all_tests